export const runtimeEnvManifest = {
  TOGETHER_API_KEY: "provider",
  EXA_API_KEY: "provider",
  WOLFRAM_ALPHA_APP_ID: "provider",
  TOGETHER_SAFETY_MODEL: "model",
  TOGETHER_COACH_MODEL: "model",
  TOGETHER_MULTIMODAL_MODEL: "model",
  TOGETHER_STT_MODEL: "model",
  TOGETHER_TTS_MODEL: "model",
  TOGETHER_TTS_RECEPTIONIST_VOICE: "model",
  TOGETHER_TTS_CALLER_VOICE: "model",
  MENTAL_HEALTH_DEMO_ENABLED: "feature",
  MENTAL_HEALTH_LIVE_CALLER_ENABLED: "feature",
  MENTAL_HEALTH_SPEECH_SECRET: "secret",
  NEXT_PUBLIC_EDGE_CASE_SEED: "public",
  HELICONE_API_KEY: "observability",
  UPSTASH_REDIS_REST_URL: "rate-limit",
  UPSTASH_REDIS_REST_TOKEN: "rate-limit",
  NETLIFY_DATABASE_URL: "database",
} as const;
